### ISSUE TITLE
Live not working on lastest version 2.6.2

### ISSUE THREAD

**Issue by MatthieuRand** [leonardoxh/race-control-tv#128] opened 2022-04-23 17:36 UTC
When I try to watch live stream the window opens nothing is loaded.
It seems that the integrated player could not open the link since when I try to open it via external players (VLC and Kodi) it says that the link could not be opened.
The inner player tries to open the link few times but nothing appears.

App version : 2.6.2
My devices : Android TV (TCL based on android 11).

**Comment by mhil70** [comment] 2022-04-24 07:18
I encountered the same issue (in latest v2.6.2).

FP1 on friday worked fine, but mayby that was because F1TV published that session without DRM.
Since the Sprint session on friday (and al subsequent sessions), the live sessions don't show.

**Comment by robbyb67** [comment] 2022-04-24 10:02
Same here

**Comment by vidje** [comment] 2022-04-24 11:57
same here, I clicked the pre-race show live now and I just get the spinning circle

**Comment by mjkarlsen** [comment] 2022-04-24 12:08
I'm having the same issue. Glad I'm not the only one 😆.

**Comment by B4579** [comment] 2022-04-24 12:23
Same here 

Device: fire tv stick

**Comment by LukasLewandowski** [comment] 2022-04-24 14:08
Same here, Philips TV with Android

**Comment by joao-bel-bynd** [comment] 2022-04-24 15:55
yup some

**Comment by JoaoPedroBelo** [comment] 2022-04-24 15:56
yup same

**Comment by pietjelombok** [comment] 2022-04-24 20:15
Me also having a loop while V2.6.2 is trying to open the live stream. Philips tv Android 9.

**Comment by leonardoxh** [comment] 2022-04-25 07:18
Duplicate of #119

**Closed by leonardoxh** 2022-04-25 07:18 UTC
