### ISSUE TITLE
Player keeps reloading 2.6.2

### ISSUE THREAD

**Issue by rsstnc147** [leonardoxh/race-control-tv#134] opened 2022-05-22 12:39 UTC
Unfortunately the player keeps reloading for me everyatime i start a video or live session. Has anyone a solution to this? I'm on a Sony Android TV. App version is 2.6.2. Cache and everything was deleted and fresh install has been done.

**Comment by sidewinder94** [comment] 2022-05-22 18:00
Sounds like a duplicate of #119

**Comment by jonathanflack** [comment] 2022-05-28 17:44
I had similar problems, but only with some videos.  As of 17:42UTC on Saturday, I am unable to successfully play the Qualifying replay, however the highlights for P3 do play without issue, as well as the Qualifying Pre-Show.  This leads me to believe that it could be some issue with permissions on the source files for those video streams?

**Closed** 2022-06-22 11:43 UTC
